### ISSUE TITLE
If the SQL execution time exceeds 10 seconds, retry is triggered and the correct result cannot be receviced

### ISSUE THREAD

**Issue by wubx** [databendcloud/metabase-databend-driver#2]
Repeat:
```
select sleep(11) a;
```

Error executing query: Error fetching next (attempts: 6, duration: PT1M1.712153625S)cause: java.io.UncheckedIOException: java.net.SocketTimeoutException: Read timed out

**Comment by flaneur2020** [comment]
@hantmac  I remember there have a timeout argument in the jdbc driver, maybe can make it a bigger value by default?

**Comment by hantmac** [comment]
> @hantmac I remember there have a timeout argument in the jdbc driver, maybe can make it a bigger value by default?

Yes, `connection_timeout` was set default 15s. But this problem seems triggered by metabase 🤔.

**Comment by hantmac** [comment]
I will try to fix this problem by adding the `socket_timeout` param in jdbc.

**Comment by hantmac** [comment]
![img_v2_9ad64cf9-403c-4189-9e01-68aaf422da8g](https://user-images.githubusercontent.com/7600925/226345912-841ef7c6-f026-466c-bfb1-6548eac5fe7d.jpg)
Fixed.
