### ISSUE TITLE
No method in multimethod 'connection-details->spec' for dispatch value: :databend

### ISSUE THREAD

**Issue by smartguo** [databendcloud/metabase-databend-driver#9]
databend：v1.2.487
metabase-databend-driver: v0.0.7
metabase：v0.49.11

**Comment by hantmac** [comment]
@smartguo Thanks for your reporting. I tested with metabase v0.49.11 and reproduce this error. But I downgrade it to v0.47.8 , it works well. 
![image](https://github.com/databendcloud/metabase-databend-driver/assets/7600925/18fee7a1-4c43-448f-9658-080878f08f7b)

So I think it maybe a bug or some thing break change in the new version of metabase and I make an issue about this in metabase, I will update here when v0.49.11 can be used OR you can use v0.47.8 instead.

**Comment by hantmac** [comment]
@smartguo Hi bro, now you can use metabase v0.0.8 on v0.49.x metabase.

**Comment by smartguo** [comment]
> @smartguo Hi bro, now you can use metabase v0.0.8 on v0.49.x metabase.

It just works!
